# Tensor Basics

## Initialization
Everything in pytorch is based on Tensor operations. A tensor can have different dimensions, so it can be 1d, 2d, or even 3d and higher -> scalar, vector, matrix, tensor.

### Import PyTorch

In [1]:
import torch

### Empty Tensor

In [2]:
x = torch.empty(1) # Scalar
print(x)

tensor([2.])


In [3]:
x = torch.empty(3) # 1D Vector
print(x)

tensor([3.1290e-20, 4.5916e-41, 0.0000e+00])


In [4]:
x = torch.empty(2, 3) # 2D Matrix
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor With Random Values

In [5]:
x = torch.rand(2, 3) # Random
print(x)

tensor([[0.9229, 0.1461, 0.0858],
        [0.6754, 0.4511, 0.7127]])


### Zeros & Ones

In [6]:
x = torch.zeros(2, 3) # Zero
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2, 3) # Zero
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor From Data

In [8]:
x = torch.tensor([1, 2, 3]) # Tensor
print(x)

tensor([1, 2, 3])


### Specific Data Type
Check and also assign data type by using dtype attribute

In [9]:
x = torch.ones(2, 3) # Zero
print(x.dtype)

torch.float32


In [10]:
x = torch.ones(2, 3, dtype=torch.int) # Zero
print(x.dtype)

torch.int32


### Size (Dimension)
Check size using the size() method.

In [11]:
x.size()

torch.Size([2, 3])

## Basic Operations

In [12]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [13]:
print(x)
print(y)

tensor([[0.8633, 0.6133],
        [0.8699, 0.7176]])
tensor([[0.8572, 0.1273],
        [0.0515, 0.4237]])


### Addition

In [14]:
z = x + y
print(z)

tensor([[1.7204, 0.7406],
        [0.9214, 1.1413]])


In [15]:
z = torch.add(x, y)
print(z)

tensor([[1.7204, 0.7406],
        [0.9214, 1.1413]])


All methods with trailing underscore will perform in-place operations

In [16]:
# In-place
y.add_(x) # y = y + x
print(y)

tensor([[1.7204, 0.7406],
        [0.9214, 1.1413]])


### Subtraction

In [17]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.8572, -0.1273],
        [-0.0515, -0.4237]])


### Multiplication

In [18]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[1.4852, 0.4542],
        [0.8015, 0.8190]])


### Division

In [19]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.5018, 0.8282],
        [0.9441, 0.6288]])


## Slicing

In [20]:
x = torch.rand(5, 3)

In [21]:
x

tensor([[0.0746, 0.5320, 0.6586],
        [0.6907, 0.5050, 0.3095],
        [0.6703, 0.5279, 0.0413],
        [0.8362, 0.8129, 0.4478],
        [0.1504, 0.4799, 0.5349]])

In [22]:
x[1, 1]

tensor(0.5050)

In [23]:
x[1, 1].item() # Get scalar value (CAN BE USED ONLY FOR A SINGLE VALUE)

0.5049786567687988

In [24]:
x[:, 2]

tensor([0.6586, 0.3095, 0.0413, 0.4478, 0.5349])

In [25]:
x[3, :]

tensor([0.8362, 0.8129, 0.4478])

In [26]:
x[1:4, 1:]

tensor([[0.5050, 0.3095],
        [0.5279, 0.0413],
        [0.8129, 0.4478]])

## Reshaping

In [27]:
x = torch.randn(4, 4)
print(x)

tensor([[-1.0704,  1.2379,  0.8063,  0.2902],
        [ 0.1961,  1.4255,  0.6262,  1.3414],
        [ 0.1782, -0.2724, -0.5296,  0.0645],
        [-0.6139, -1.0853, -1.1031,  0.0992]])


In [28]:
y = x.view(16) # No. of elements must match
print(y)

tensor([-1.0704,  1.2379,  0.8063,  0.2902,  0.1961,  1.4255,  0.6262,  1.3414,
         0.1782, -0.2724, -0.5296,  0.0645, -0.6139, -1.0853, -1.1031,  0.0992])


In [29]:
y = x.view(-1, 8) # -1 -> Automatically calculate required size
print(y)

tensor([[-1.0704,  1.2379,  0.8063,  0.2902,  0.1961,  1.4255,  0.6262,  1.3414],
        [ 0.1782, -0.2724, -0.5296,  0.0645, -0.6139, -1.0853, -1.1031,  0.0992]])


## NumPy Array <-> PyTorch Tensor

In [30]:
import numpy as np

If tensor is stored in the CPU instead of the GPU it will be the same object as the converetd numpy array.

In [31]:
a = torch.ones(5)
print(a, type(a))

b = a.numpy()
print(b, type(b))

a.add_(1)
print(a, b) # Both are changed

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [32]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b) # Both are changed

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Operations will be much faster in GPU but they cappot be converted to numpy as numpy works with CPU.

In [33]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    # Move to device
    y = torch.ones(5)
    y = y.to(device)
    print(x, y)
    # To numpy
    z = x + y
    z = z.to("cpu")
    z = z.numpy()
    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0') tensor([1., 1., 1., 1., 1.], device='cuda:0')
[2. 2. 2. 2. 2.]
