# Tensor Basics

## Initialization
Everything in pytorch is based on Tensor operations. A tensor can have different dimensions, so it can be 1d, 2d, or even 3d and higher -> scalar, vector, matrix, tensor.

### Import PyTorch

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

### Empty Tensor

In [3]:
x = torch.empty(1) # Scalar
print(x)

tensor([1.4013e-44])


In [4]:
x = torch.empty(3) # 1D Vector
print(x)

tensor([0., 0., 0.])


In [5]:
x = torch.empty(2, 3) # 2D Matrix
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor With Random Values

In [6]:
x = torch.rand(2, 3) # Random
print(x)

tensor([[0.6332, 0.3933, 0.9483],
        [0.0221, 0.9051, 0.2990]])


### Zeros & Ones

In [7]:
x = torch.zeros(2, 3) # Zero
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.ones(2, 3) # Zero
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor From Data

In [9]:
x = torch.tensor([1, 2, 3]) # Tensor
print(x)

tensor([1, 2, 3])


### Specific Data Type
Check and also assign data type by using dtype attribute

In [10]:
x = torch.ones(2, 3) # Zero
print(x.dtype)

torch.float32


In [11]:
x = torch.ones(2, 3, dtype=torch.int) # Zero
print(x.dtype)

torch.int32


### Size (Dimension)
Check size using the size() method.

In [12]:
x.size()

torch.Size([2, 3])

## Basic Operations

In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [14]:
print(x)
print(y)

tensor([[0.1689, 0.3786],
        [0.3084, 0.1787]])
tensor([[0.4166, 0.5713],
        [0.7240, 0.6723]])


### Addition

In [15]:
z = x + y
print(z)

tensor([[0.5854, 0.9499],
        [1.0324, 0.8510]])


In [16]:
z = torch.add(x, y)
print(z)

tensor([[0.5854, 0.9499],
        [1.0324, 0.8510]])


All methods with trailing underscore will perform in-place operations

In [17]:
# In-place
y.add_(x) # y = y + x
print(y)

tensor([[0.5854, 0.9499],
        [1.0324, 0.8510]])


### Subtraction

In [18]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.4166, -0.5713],
        [-0.7240, -0.6723]])


### Multiplication

In [19]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[0.0989, 0.3596],
        [0.3184, 0.1520]])


### Division

In [20]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.2885, 0.3986],
        [0.2987, 0.2099]])


## Slicing

In [21]:
x = torch.rand(5, 3)

In [22]:
x

tensor([[0.1973, 0.1235, 0.7633],
        [0.7159, 0.5885, 0.5997],
        [0.4525, 0.5310, 0.1992],
        [0.0913, 0.4279, 0.8001],
        [0.3164, 0.0084, 0.5960]])

In [23]:
x[1, 1]

tensor(0.5885)

In [24]:
x[1, 1].item() # Get scalar value (CAN BE USED ONLY FOR A SINGLE VALUE)

0.5885105133056641

In [25]:
x[:, 2]

tensor([0.7633, 0.5997, 0.1992, 0.8001, 0.5960])

In [26]:
x[3, :]

tensor([0.0913, 0.4279, 0.8001])

In [27]:
x[1:4, 1:]

tensor([[0.5885, 0.5997],
        [0.5310, 0.1992],
        [0.4279, 0.8001]])

## Reshaping

In [28]:
x = torch.randn(4, 4)
print(x)

tensor([[ 0.9318, -0.9118,  0.7687, -1.0103],
        [ 0.5820,  1.1821,  0.0164,  0.4086],
        [-0.9591, -0.4691, -1.1126,  1.7101],
        [-1.1335,  0.3961, -1.0236, -0.0266]])


In [29]:
y = x.view(16) # No. of elements must match
print(y)

tensor([ 0.9318, -0.9118,  0.7687, -1.0103,  0.5820,  1.1821,  0.0164,  0.4086,
        -0.9591, -0.4691, -1.1126,  1.7101, -1.1335,  0.3961, -1.0236, -0.0266])


In [30]:
y = x.view(-1, 8) # -1 -> Automatically calculate required size
print(y)

tensor([[ 0.9318, -0.9118,  0.7687, -1.0103,  0.5820,  1.1821,  0.0164,  0.4086],
        [-0.9591, -0.4691, -1.1126,  1.7101, -1.1335,  0.3961, -1.0236, -0.0266]])


## NumPy Array <-> PyTorch Tensor

In [31]:
import numpy as np

If tensor is stored in the CPU instead of the GPU it will be the same object as the converetd numpy array.

In [32]:
a = torch.ones(5)
print(a, type(a))

b = a.numpy()
print(b, type(b))

a.add_(1)
print(a, b) # Both are changed

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [33]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b) # Both are changed

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Operations will be much faster in GPU but they cappot be converted to numpy as numpy works with CPU.

In [34]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    # Move to device
    y = torch.ones(5)
    y = y.to(device)
    print(x, y)
    # To numpy
    z = x + y
    z = z.to("cpu")
    z = z.numpy()
    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0') tensor([1., 1., 1., 1., 1.], device='cuda:0')
[2. 2. 2. 2. 2.]
