In [1]:
import torch

c:\Users\msoum\anaconda3\envs\pytorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Torch Tensors

In [2]:
# This is a 1D tensor
a = torch.tensor([1, 2, 3, 4, 5])
print(a)

tensor([1, 2, 3, 4, 5])


In [3]:
# This is a 2D tensor
b = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [4]:
# Print the size of the tensors
print(a.shape) # attribute
print(b.shape)
print(a.size()) # method
print(b.size())

torch.Size([5])
torch.Size([4, 3])
torch.Size([5])
torch.Size([4, 3])


In [5]:
# Get the height or number of rows of the tensor
print(b.shape[0])

4


In [6]:
# FLoat tensor
c = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# or
c = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.float32)

In [7]:
d = torch.DoubleTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# or
d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())
print(d.mean())

tensor(6.5000)
tensor(6.5000, dtype=torch.float64)


In [11]:
print(c.std())
print(d.std())

tensor(3.6056)
tensor(3.6056, dtype=torch.float64)


In [12]:
# Reshape tensor b
print(b.view(-1, 1))
# -1 means that the number of rows is inferred from the number of columns
print(b.view(12))
print(b.view(-1, 4))
print(b.view(3, 4))
# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


In [13]:
# We can even reshape 3D tensors
# Create a 3D tensor with 2 channels, 3 rows and 4 columns
three_dim = torch.randn(2, 3, 4)
print('\n', three_dim)
print(three_dim.view(2, 12)) # 2 rows, 12 columns
print(three_dim.view(2, -1)) # 2 rows, 12 columns


 tensor([[[-1.1578, -1.2573,  0.7889, -1.7437],
         [-2.5723, -0.7763,  0.4638, -0.8156],
         [-0.4233, -0.1946,  0.2935, -0.7129]],

        [[ 0.7075,  0.5952,  0.2102,  1.5795],
         [ 1.2752, -0.3219, -0.5435,  0.0923],
         [-1.8794,  0.4439,  0.9908,  0.2845]]])
tensor([[-1.1578, -1.2573,  0.7889, -1.7437, -2.5723, -0.7763,  0.4638, -0.8156,
         -0.4233, -0.1946,  0.2935, -0.7129],
        [ 0.7075,  0.5952,  0.2102,  1.5795,  1.2752, -0.3219, -0.5435,  0.0923,
         -1.8794,  0.4439,  0.9908,  0.2845]])
tensor([[-1.1578, -1.2573,  0.7889, -1.7437, -2.5723, -0.7763,  0.4638, -0.8156,
         -0.4233, -0.1946,  0.2935, -0.7129],
        [ 0.7075,  0.5952,  0.2102,  1.5795,  1.2752, -0.3219, -0.5435,  0.0923,
         -1.8794,  0.4439,  0.9908,  0.2845]])


In [14]:
# Create a matrix with random numebrs between 0 and 1
r = torch.rand(4, 4)
print(r)

tensor([[0.9395, 0.1156, 0.8028, 0.9423],
        [0.9518, 0.0941, 0.8946, 0.0896],
        [0.4078, 0.1176, 0.9861, 0.2800],
        [0.4663, 0.5697, 0.7999, 0.7461]])


In [15]:
# Create a matrix with random numbers from a normal distribution with mean 0 and standard deviation 1
r2 = torch.randn(4, 4)
print(r2)
print(r2.dtype)
print(r2.mean(), r2.std())

tensor([[ 1.1202, -0.0903, -0.0327,  0.5418],
        [ 1.7852,  1.1013, -1.3814,  0.6923],
        [-1.0597, -0.8378, -0.2065, -1.3389],
        [ 0.5777, -0.8900,  0.0496, -0.6558]])
torch.float32
tensor(-0.0391) tensor(0.9501)


In [16]:
# Create an array of 5 random integers between 6 and 10 (exclusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)
print(in_array.dtype)

tensor([6, 8, 9, 6, 8])
torch.int64


In [17]:
in_array2 = torch.randint(6, 10, (3, 3))
print(in_array2)
print(in_array2.dtype)

tensor([[9, 6, 8],
        [9, 9, 7],
        [6, 9, 7]])
torch.int64


In [18]:
# Get the number of elements in the tensor
print(in_array.numel())
print(in_array2.numel())
# or
print(torch.numel(in_array2))

5
9
9


In [19]:
# Construct a tensor of zeros and dtype long
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
# Construct a tensor of ones
o = torch.ones(3, 3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [20]:
# Construct a tensor of ones with the same shape as the tensor r2
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-1.1174, -0.1164,  0.2848,  1.3215],
        [-1.2028, -0.3561,  0.1400, -0.2151],
        [ 0.1171,  0.0674,  0.7190, -1.1660],
        [ 0.6891, -1.7614,  0.3992, -0.8868]], dtype=torch.float64)


In [21]:
# Add two tensors. Make sure they have the same shape and type
add_result = torch.add(r2, r2_like)

In [22]:
# In-place addition
# For in-place operations, add an underscore to the end of the function name
r2.add_(r2_like)
print(r2)

tensor([[ 0.0028, -0.2067,  0.2522,  1.8632],
        [ 0.5824,  0.7452, -1.2414,  0.4772],
        [-0.9426, -0.7704,  0.5125, -2.5049],
        [ 1.2667, -2.6514,  0.4488, -1.5426]])


In [23]:
# Slice tensors
print(r2[:, 1]) # all rows, column 1
print(r2[:, :2]) # all rows, columns 0 and 1
print(r2[:3, :]) # rows 0, 1 and 2, all columns
num = r2[2, 3] # index 2, 3
print(num)
print(num.item())

tensor([-0.2067,  0.7452, -0.7704, -2.6514])
tensor([[ 0.0028, -0.2067],
        [ 0.5824,  0.7452],
        [-0.9426, -0.7704],
        [ 1.2667, -2.6514]])
tensor([[ 0.0028, -0.2067,  0.2522,  1.8632],
        [ 0.5824,  0.7452, -1.2414,  0.4772],
        [-0.9426, -0.7704,  0.5125, -2.5049]])
tensor(-2.5049)
-2.5049209594726562


### Numpy Bridge

In [24]:
import numpy as np

In [25]:
# Convert a Torch tensor to a NumPy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# See how the numpy array changed in value
a.add_(1)
print(a, b) # Both a and b changed

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [26]:
# Convert a NumPy array to a Torch tensor
# See how changing the np array changed the Torch tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
a += 1 # np.add(a, 1, out=a)
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
# Move tensor to GPU
r2 = r2.to('cuda') # or r2.cuda()

In [28]:
# Preferred
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
r2 = r2.to(device)


In [29]:
# Convert list to tensor
a = [1, 2, 3, 4, 5]
to_tensor = torch.tensor(a)
print(to_tensor, to_tensor.dtype)

tensor([1, 2, 3, 4, 5]) torch.int64


### Tensor Concatenation

In [30]:
first_1 = torch.randn(2, 5)
second_1 = torch.randn(3, 5)
print(first_1)
print(second_1)
con_1 = torch.cat((first_1, second_1), dim=0) # dim=0 means concatenate along the rows (default)
print("\n", con_1, "\n")
first_2 = torch.randn(2, 5)
second_2 = torch.randn(2, 5)
print(first_2)
print(second_2)
con_2 = torch.cat((first_2, second_2), dim=1) # dim=1 means concatenate along the columns
print("\n", con_2)


tensor([[ 0.0326,  1.4760, -0.5709,  1.0788,  0.5675],
        [ 0.2532, -3.0515,  0.0968,  2.6989, -0.2675]])
tensor([[ 0.5654,  0.3757, -1.3545, -1.4248,  1.4370],
        [-0.1584, -0.1116, -1.0834, -0.5363,  1.3603],
        [ 1.2537,  2.5982, -2.6177,  0.3330,  2.3066]])

 tensor([[ 0.0326,  1.4760, -0.5709,  1.0788,  0.5675],
        [ 0.2532, -3.0515,  0.0968,  2.6989, -0.2675],
        [ 0.5654,  0.3757, -1.3545, -1.4248,  1.4370],
        [-0.1584, -0.1116, -1.0834, -0.5363,  1.3603],
        [ 1.2537,  2.5982, -2.6177,  0.3330,  2.3066]]) 

tensor([[ 2.0047,  0.4988, -0.8801, -0.1944, -0.7267],
        [ 0.2589,  0.1650, -1.9592, -0.2649, -0.0933]])
tensor([[ 0.9353, -0.8974,  0.4215, -0.1061,  0.2643],
        [ 1.2574,  0.8428,  0.3727,  0.0882,  0.0999]])

 tensor([[ 2.0047,  0.4988, -0.8801, -0.1944, -0.7267,  0.9353, -0.8974,  0.4215,
         -0.1061,  0.2643],
        [ 0.2589,  0.1650, -1.9592, -0.2649, -0.0933,  1.2574,  0.8428,  0.3727,
          0.0882,  0.0999]])


In [31]:
# Add a dimension to a tensor
tensor_1 = torch.tensor([1, 2, 3, 4])

tensor_a = torch.unsqueeze(tensor_1, dim=0) # add a dimension at index 0
print(tensor_a)
print(tensor_a.shape)

tensor_a = torch.unsqueeze(tensor_1, dim=1) # add a dimension at index 1
print(tensor_a)
print(tensor_a.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [32]:
tensor_2 = torch.rand(2, 3, 4)
print(tensor_2)
print()

tensor_c = tensor_2[:, :, 2]
print(tensor_c)
print(tensor_c.shape)
print()

tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[[0.8213, 0.3052, 0.0924, 0.0035],
         [0.7343, 0.8783, 0.7631, 0.2915],
         [0.9435, 0.1688, 0.6070, 0.4355]],

        [[0.6123, 0.0481, 0.7928, 0.2274],
         [0.7874, 0.4462, 0.4780, 0.6148],
         [0.2419, 0.2469, 0.1664, 0.7117]]])

tensor([[0.0924, 0.7631, 0.6070],
        [0.7928, 0.4780, 0.1664]])
torch.Size([2, 3])

tensor([[[0.0924],
         [0.7631],
         [0.6070]],

        [[0.7928],
         [0.4780],
         [0.1664]]])
torch.Size([2, 3, 1])


### Autograd

In [34]:
# If requires_grad=True, the tensor will track all operations on it
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)
# z knows that it was created as a result of an operation, so it has a grad_fn
print(z.grad_fn)
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [35]:
# Backpropagation - compute the gradient of s with respect to the tensors x and y
s.backward()
print(x.grad, y.grad)

tensor([1., 1., 1.]) tensor([1., 1., 1.])


In [40]:
# By default, tensors have requires_grad=False, so they do not track history
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
print(x.requires_grad, y.requires_grad)
z = x + y
# z has no grad_fn because x and y were not created with requires_grad=True
print(z.grad_fn)
# Another way to set requires_grad is to use the .requires_grad_() method
x.requires_grad_()
y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

new_z = z.detach()
# z.detach() returns a tensor that shares the same storage as z, but with the computation history forgotten
print(new_z.grad_fn)
# It doesn't know anything about how it was computed

# You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad():
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

False False
None
True
None
True
True
False
