# Loss Functions

In [1]:
import torch
import torch.nn as nn

c:\Users\msoum\anaconda3\envs\pytorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


### Mean Squared Error

In [2]:
predictions = torch.randn(4, 5)
predictions

tensor([[ 1.4569, -0.4753, -0.7340, -0.6037, -0.2985],
        [-0.2754,  0.2691,  0.5658,  1.3251,  0.1771],
        [-0.3099, -1.0515,  0.4776,  0.7341,  0.1367],
        [ 2.5716, -2.7260,  2.4209, -0.8000,  0.6064]])

In [3]:
labels = torch.randn(4, 5)
labels

tensor([[ 0.0581, -0.2909, -0.9907, -0.9298, -1.0880],
        [ 0.1755, -0.4043,  0.5390, -0.7451, -1.4748],
        [ 0.6728,  2.1813,  0.2465, -0.8059,  0.6819],
        [ 0.6223, -2.6502, -0.5554,  1.5489, -0.0048]])

In [4]:
mse = nn.MSELoss(reduction='none') # reduction='none' means no reduction

In [5]:
loss = mse(predictions, labels)
loss

tensor([[1.9566e+00, 3.4018e-02, 6.5905e-02, 1.0631e-01, 6.2339e-01],
        [2.0335e-01, 4.5352e-01, 7.2277e-04, 4.2856e+00, 2.7287e+00],
        [9.6568e-01, 1.0451e+01, 5.3403e-02, 2.3714e+00, 2.9716e-01],
        [3.7998e+00, 5.7406e-03, 8.8582e+00, 5.5176e+00, 3.7355e-01]])

In [6]:
mse = nn.MSELoss(reduction='mean') # default
loss = mse(predictions, labels)
loss

tensor(2.1576)

In [7]:
# Manually
((predictions - labels) ** 2).mean()

tensor(2.1576)

### Binary Cross Entropy Loss

In [8]:
predictions

tensor([[ 1.4569, -0.4753, -0.7340, -0.6037, -0.2985],
        [-0.2754,  0.2691,  0.5658,  1.3251,  0.1771],
        [-0.3099, -1.0515,  0.4776,  0.7341,  0.1367],
        [ 2.5716, -2.7260,  2.4209, -0.8000,  0.6064]])

In [11]:
labels = torch.empty(4, 5).random_(0, 2)
labels


tensor([[1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 1., 0.]])

In [12]:
sigmoid = nn.Sigmoid()

In [13]:
bce = nn.BCELoss(reduction='mean')

In [14]:
bce(sigmoid(predictions), labels)

tensor(0.7789)

In [15]:
bce_with_logits = nn.BCEWithLogitsLoss(reduction='mean') # sigmoid + bce
bce_with_logits(predictions, labels)

tensor(0.7789)

In [21]:
# Manually
import numpy as np
x = predictions.numpy()
y = labels.numpy()

In [22]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [23]:
x = sigmoid(x)
loss_values = np.zeros(y.shape)
for i in range(len(y)):
    batch_loss = np.zeros(y[i].shape)
    for j in range(len(y[0])):
        batch_loss[j] = -np.log(x[i][j]) if y[i][j] == 1 else -np.log(1 - x[i][j])
    loss_values[i] = batch_loss
print(loss_values.mean())

0.778885051633756


### Cross Entropy Loss

Execution same as above but for labels, no need to provide one-hot vector. Just give the corrrect label indices. It will automatically perform one-hot encoding.  
Example:   
Input (predictions) = N x C dimension   
Target (labels) = N dimension where 0 < each value < C - 1